"""estrutura inicial

Cria as 19 tabelas da plataforma familiar: identidade e familias,
objetivos e ocorrencias, sessoes com capturas e localizacoes, livro-razao
de pontos, trilhas de recompensa, notificacoes e auditoria.

Gerada a partir de Base.metadata, e nao por autogenerate: o ambiente de
desenvolvimento nao tem PostgreSQL vivo para o Alembic comparar. O SQL
resultante foi conferido em modo offline (`alembic upgrade head --sql`).

Revision ID: 0001_estrutura_inicial
Revises:
Create Date: 2026-08-19
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_estrutura_inicial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('users',
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('senha_hash', sa.String(length=255), nullable=False),
        sa.Column('nome_exibicao', sa.String(length=120), nullable=False),
        sa.Column('avatar_caminho', sa.String(length=500), nullable=True),
        sa.Column('nascimento', sa.Date(), nullable=True),
        sa.Column('ativo', sa.Boolean(), nullable=False),
        sa.Column('ultimo_login_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('char_length(username) >= 3', name=op.f('ck_users_username_minimo')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
        sa.UniqueConstraint('email', name=op.f('uq_users_email')),
        sa.UniqueConstraint('username', name=op.f('uq_users_username'))
        )
        op.create_table('devices',
        sa.Column('usuario_id', sa.UUID(), nullable=False),
        sa.Column('instalacao_id', sa.String(length=128), nullable=False),
        sa.Column('plataforma', postgresql.ENUM('WEB', 'ANDROID', name='plataforma'), nullable=False),
        sa.Column('modelo', sa.String(length=120), nullable=True),
        sa.Column('versao_android', sa.String(length=30), nullable=True),
        sa.Column('versao_app', sa.String(length=30), nullable=True),
        sa.Column('pode_capturar', sa.Boolean(), nullable=False),
        sa.Column('pode_localizar', sa.Boolean(), nullable=False),
        sa.Column('pode_sobrepor', sa.Boolean(), nullable=False),
        sa.Column('ultimo_acesso_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name=op.f('fk_devices_usuario_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
        sa.UniqueConstraint('usuario_id', 'instalacao_id', name='instalacao_unica_por_usuario')
        )
        op.create_table('families',
        sa.Column('nome', sa.String(length=120), nullable=False),
        sa.Column('dono_id', sa.UUID(), nullable=False),
        sa.Column('intervalo_captura_seg', sa.Integer(), nullable=False),
        sa.Column('retencao_captura_dias', sa.Integer(), nullable=False),
        sa.Column('exige_localizacao', sa.Boolean(), nullable=False),
        sa.Column('pontos_por_minuto', sa.Integer(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('intervalo_captura_seg BETWEEN 60 AND 3600', name=op.f('ck_families_intervalo_captura_razoavel')),
        sa.CheckConstraint('retencao_captura_dias BETWEEN 1 AND 90', name=op.f('ck_families_retencao_razoavel')),
        sa.ForeignKeyConstraint(['dono_id'], ['users.id'], name=op.f('fk_families_dono_id_users'), ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_families'))
        )
        op.create_table('audit_logs',
        sa.Column('ator_id', sa.UUID(), nullable=True),
        sa.Column('familia_id', sa.UUID(), nullable=True),
        sa.Column('acao', sa.String(length=80), nullable=False),
        sa.Column('recurso_tipo', sa.String(length=60), nullable=False),
        sa.Column('recurso_id', sa.UUID(), nullable=True),
        sa.Column('metadados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('ip', postgresql.INET(), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['ator_id'], ['users.id'], name=op.f('fk_audit_logs_ator_id_users'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['familia_id'], ['families.id'], name=op.f('fk_audit_logs_familia_id_families'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
        )
        op.create_table('family_members',
        sa.Column('familia_id', sa.UUID(), nullable=False),
        sa.Column('usuario_id', sa.UUID(), nullable=False),
        sa.Column('papel', postgresql.ENUM('ADMIN', 'DEPENDENTE', name='papel_familiar'), nullable=False),
        sa.Column('parentesco', sa.String(length=60), nullable=True),
        sa.Column('status', postgresql.ENUM('ATIVO', 'SUSPENSO', 'REMOVIDO', name='status_membro'), nullable=False),
        sa.Column('criado_por_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], name=op.f('fk_family_members_criado_por_id_users'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['familia_id'], ['families.id'], name=op.f('fk_family_members_familia_id_families'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name=op.f('fk_family_members_usuario_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_family_members')),
        sa.UniqueConstraint('familia_id', 'usuario_id', name='membro_unico_por_familia')
        )
        op.create_table('known_locations',
        sa.Column('familia_id', sa.UUID(), nullable=False),
        sa.Column('nome', sa.String(length=80), nullable=False),
        sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column('raio_metros', sa.Integer(), nullable=False),
        sa.Column('ativo', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_known_locations_latitude_valida')),
        sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_known_locations_longitude_valida')),
        sa.CheckConstraint('raio_metros BETWEEN 20 AND 5000', name=op.f('ck_known_locations_raio_razoavel')),
        sa.ForeignKeyConstraint(['familia_id'], ['families.id'], name=op.f('fk_known_locations_familia_id_families'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_known_locations')),
        sa.UniqueConstraint('familia_id', 'nome', name='local_unico_por_familia')
        )
        op.create_table('notifications',
        sa.Column('destinatario_id', sa.UUID(), nullable=False),
        sa.Column('familia_id', sa.UUID(), nullable=False),
        sa.Column('tipo', sa.String(length=60), nullable=False),
        sa.Column('titulo', sa.String(length=160), nullable=False),
        sa.Column('mensagem', sa.Text(), nullable=False),
        sa.Column('dados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('lida_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['destinatario_id'], ['users.id'], name=op.f('fk_notifications_destinatario_id_users'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['familia_id'], ['families.id'], name=op.f('fk_notifications_familia_id_families'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
        )
        op.create_table('refresh_tokens',
        sa.Column('usuario_id', sa.UUID(), nullable=False),
        sa.Column('token_hash', sa.String(length=128), nullable=False),
        sa.Column('dispositivo_id', sa.UUID(), nullable=True),
        sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('substituido_por_id', sa.UUID(), nullable=True),
        sa.Column('ip', postgresql.INET(), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['dispositivo_id'], ['devices.id'], name=op.f('fk_refresh_tokens_dispositivo_id_devices'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['substituido_por_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_substituido_por_id_refresh_tokens'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name=op.f('fk_refresh_tokens_usuario_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
        sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
        )
        op.create_table('reward_tracks',
        sa.Column('beneficiario_id', sa.UUID(), nullable=False),
        sa.Column('familia_id', sa.UUID(), nullable=False),
        sa.Column('criador_id', sa.UUID(), nullable=True),
        sa.Column('nome', sa.String(length=120), nullable=False),
        sa.Column('escopo', postgresql.ENUM('TODOS', 'MATERIA', 'OBJETIVO', 'CONJUNTO', name='escopo_trilha'), nullable=False),
        sa.Column('filtro', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('ativo', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['beneficiario_id'], ['users.id'], name=op.f('fk_reward_tracks_beneficiario_id_users'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['criador_id'], ['users.id'], name=op.f('fk_reward_tracks_criador_id_users'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['familia_id'], ['families.id'], name=op.f('fk_reward_tracks_familia_id_families'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_reward_tracks'))
        )
        op.create_table('subjects',
        sa.Column('familia_id', sa.UUID(), nullable=False),
        sa.Column('nome', sa.String(length=80), nullable=False),
        sa.Column('cor', sa.String(length=7), nullable=True),
        sa.Column('icone', sa.String(length=40), nullable=True),
        sa.Column('ativo', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['familia_id'], ['families.id'], name=op.f('fk_subjects_familia_id_families'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
        sa.UniqueConstraint('familia_id', 'nome', name='materia_unica_por_familia')
        )
        op.create_table('objectives',
        sa.Column('familia_id', sa.UUID(), nullable=False),
        sa.Column('titular_id', sa.UUID(), nullable=False),
        sa.Column('criador_id', sa.UUID(), nullable=True),
        sa.Column('materia_id', sa.UUID(), nullable=True),
        sa.Column('tipo', postgresql.ENUM('ESTUDO', 'TAREFA', name='tipo_objetivo'), nullable=False),
        sa.Column('nome', sa.String(length=160), nullable=False),
        sa.Column('descricao', sa.Text(), nullable=True),
        sa.Column('meta_periodo', sa.Integer(), nullable=False),
        sa.Column('meta_total', sa.Integer(), nullable=True),
        sa.Column('frequencia', postgresql.ENUM('DIARIA', 'SEMANAL', 'MENSAL', 'PERSONALIZADA', name='frequencia'), nullable=False),
        sa.Column('dias_semana', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('horario_sugerido', sa.String(length=5), nullable=True),
        sa.Column('inicia_em', sa.Date(), nullable=True),
        sa.Column('prazo_final', sa.Date(), nullable=True),
        sa.Column('acumula_pendencia', sa.Boolean(), nullable=False),
        sa.Column('permite_adiantar', sa.Boolean(), nullable=False),
        sa.Column('max_adiantamentos', sa.SmallInteger(), nullable=False),
        sa.Column('adiantamento_exige_aprovacao', sa.Boolean(), nullable=False),
        sa.Column('exige_sessao_verificada', sa.Boolean(), nullable=False),
        sa.Column('limite_pontos_dia', sa.Integer(), nullable=True),
        sa.Column('pontos_fixos', sa.Integer(), nullable=True),
        sa.Column('exige_aprovacao_final', sa.Boolean(), nullable=False),
        sa.Column('status', postgresql.ENUM('ANDAMENTO', 'PAUSADO', 'CONCLUIDO', 'ARQUIVADO', name='status_objetivo'), nullable=False),
        sa.Column('arquivado_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("tipo <> 'task' OR pontos_fixos IS NOT NULL", name=op.f('ck_objectives_tarefa_tem_pontos_fixos')),
        sa.CheckConstraint('max_adiantamentos BETWEEN 0 AND 30', name=op.f('ck_objectives_adiantamento_razoavel')),
        sa.CheckConstraint('meta_periodo > 0', name=op.f('ck_objectives_meta_positiva')),
        sa.CheckConstraint('meta_total IS NULL OR meta_total > 0', name=op.f('ck_objectives_total_positivo')),
        sa.CheckConstraint('prazo_final IS NULL OR inicia_em IS NULL OR prazo_final >= inicia_em', name=op.f('ck_objectives_prazo_depois_do_inicio')),
        sa.ForeignKeyConstraint(['criador_id'], ['users.id'], name=op.f('fk_objectives_criador_id_users'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['familia_id'], ['families.id'], name=op.f('fk_objectives_familia_id_families'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['materia_id'], ['subjects.id'], name=op.f('fk_objectives_materia_id_subjects'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['titular_id'], ['users.id'], name=op.f('fk_objectives_titular_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_objectives'))
        )
        op.create_table('reward_levels',
        sa.Column('trilha_id', sa.UUID(), nullable=False),
        sa.Column('numero', sa.SmallInteger(), nullable=False),
        sa.Column('pontos_necessarios', sa.Integer(), nullable=False),
        sa.Column('premio', sa.String(length=200), nullable=False),
        sa.Column('ativo', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('numero > 0', name=op.f('ck_reward_levels_numero_positivo')),
        sa.CheckConstraint('pontos_necessarios > 0', name=op.f('ck_reward_levels_pontos_positivos')),
        sa.ForeignKeyConstraint(['trilha_id'], ['reward_tracks.id'], name=op.f('fk_reward_levels_trilha_id_reward_tracks'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_reward_levels')),
        sa.UniqueConstraint('trilha_id', 'numero', name='nivel_unico_na_trilha')
        )
        op.create_table('objective_occurrences',
        sa.Column('objetivo_id', sa.UUID(), nullable=False),
        sa.Column('titular_id', sa.UUID(), nullable=False),
        sa.Column('prevista_para', sa.Date(), nullable=False),
        sa.Column('meta', sa.Integer(), nullable=False),
        sa.Column('realizado', sa.Integer(), nullable=False),
        sa.Column('status', postgresql.ENUM('PENDENTE', 'CONCLUIDA', 'PERDIDA', name='status_ocorrencia'), nullable=False),
        sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('momento_conclusao', postgresql.ENUM('NO_PRAZO', 'ATRASADA', 'ADIANTADA', name='momento_conclusao'), nullable=True),
        sa.Column('dias_adiantados', sa.SmallInteger(), nullable=False),
        sa.Column('sessao_conclusao_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('dias_adiantados >= 0', name=op.f('ck_objective_occurrences_adiantamento_nao_negativo')),
        sa.CheckConstraint('realizado >= 0', name=op.f('ck_objective_occurrences_realizado_nao_negativo')),
        sa.ForeignKeyConstraint(['objetivo_id'], ['objectives.id'], name=op.f('fk_objective_occurrences_objetivo_id_objectives'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sessao_conclusao_id'], ['study_sessions.id'], name='fk_occurrence_sessao_conclusao', ondelete='SET NULL', use_alter=True),
        sa.ForeignKeyConstraint(['titular_id'], ['users.id'], name=op.f('fk_objective_occurrences_titular_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_objective_occurrences')),
        sa.UniqueConstraint('objetivo_id', 'prevista_para', name='ocorrencia_unica_por_data')
        )
        op.create_table('reward_unlocks',
        sa.Column('nivel_id', sa.UUID(), nullable=False),
        sa.Column('beneficiario_id', sa.UUID(), nullable=False),
        sa.Column('status', postgresql.ENUM('BLOQUEADA', 'DESBLOQUEADA', 'SOLICITADA', 'ENTREGUE', name='status_recompensa'), nullable=False),
        sa.Column('desbloqueado_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('solicitado_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('entregue_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('confirmado_por_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['beneficiario_id'], ['users.id'], name=op.f('fk_reward_unlocks_beneficiario_id_users'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['confirmado_por_id'], ['users.id'], name=op.f('fk_reward_unlocks_confirmado_por_id_users'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['nivel_id'], ['reward_levels.id'], name=op.f('fk_reward_unlocks_nivel_id_reward_levels'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_reward_unlocks')),
        sa.UniqueConstraint('nivel_id', 'beneficiario_id', name='desbloqueio_unico')
        )
        op.create_table('study_sessions',
        sa.Column('ocorrencia_id', sa.UUID(), nullable=True),
        sa.Column('objetivo_id', sa.UUID(), nullable=False),
        sa.Column('usuario_id', sa.UUID(), nullable=False),
        sa.Column('familia_id', sa.UUID(), nullable=False),
        sa.Column('dispositivo_id', sa.UUID(), nullable=True),
        sa.Column('tipo', postgresql.ENUM('NORMAL', 'VERIFICADA', name='tipo_sessao'), nullable=False),
        sa.Column('estado', postgresql.ENUM('ATIVA', 'PAUSADA', 'INTERROMPIDA', 'FINALIZADA', name='estado_sessao'), nullable=False),
        sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('pausada_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('retomada_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('finalizada_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('ultimo_heartbeat_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('segundos_brutos', sa.Integer(), nullable=False),
        sa.Column('segundos_validos', sa.Integer(), nullable=False),
        sa.Column('segundos_verificados', sa.Integer(), nullable=False),
        sa.Column('segundos_nao_verificados', sa.Integer(), nullable=False),
        sa.Column('motivo_interrupcao', sa.String(length=80), nullable=True),
        sa.Column('exige_captura', sa.Boolean(), nullable=False),
        sa.Column('exige_localizacao', sa.Boolean(), nullable=False),
        sa.Column('intervalo_captura_seg', sa.Integer(), nullable=True),
        sa.Column('resumo_final', sa.Text(), nullable=True),
        sa.Column('aprovada_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('aprovada_por_id', sa.UUID(), nullable=True),
        sa.Column('chave_finalizacao', sa.String(length=64), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('finalizada_em IS NULL OR finalizada_em >= iniciada_em', name=op.f('ck_study_sessions_fim_depois_do_inicio')),
        sa.CheckConstraint('segundos_brutos >= 0', name=op.f('ck_study_sessions_brutos_nao_negativos')),
        sa.CheckConstraint('segundos_validos <= segundos_brutos', name=op.f('ck_study_sessions_validos_cabem_no_bruto')),
        sa.CheckConstraint('segundos_validos >= 0', name=op.f('ck_study_sessions_validos_nao_negativos')),
        sa.CheckConstraint('segundos_verificados + segundos_nao_verificados <= segundos_brutos', name=op.f('ck_study_sessions_verificado_cabe_no_bruto')),
        sa.ForeignKeyConstraint(['aprovada_por_id'], ['users.id'], name=op.f('fk_study_sessions_aprovada_por_id_users'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['dispositivo_id'], ['devices.id'], name=op.f('fk_study_sessions_dispositivo_id_devices'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['familia_id'], ['families.id'], name=op.f('fk_study_sessions_familia_id_families'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['objetivo_id'], ['objectives.id'], name=op.f('fk_study_sessions_objetivo_id_objectives'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['ocorrencia_id'], ['objective_occurrences.id'], name=op.f('fk_study_sessions_ocorrencia_id_objective_occurrences'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name=op.f('fk_study_sessions_usuario_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions')),
        sa.UniqueConstraint('chave_finalizacao', name=op.f('uq_study_sessions_chave_finalizacao'))
        )
        op.create_table('point_ledger',
        sa.Column('beneficiario_id', sa.UUID(), nullable=False),
        sa.Column('familia_id', sa.UUID(), nullable=False),
        sa.Column('objetivo_id', sa.UUID(), nullable=True),
        sa.Column('materia_id', sa.UUID(), nullable=True),
        sa.Column('sessao_id', sa.UUID(), nullable=True),
        sa.Column('ocorrencia_id', sa.UUID(), nullable=True),
        sa.Column('pontos', sa.Integer(), nullable=False),
        sa.Column('origem', postgresql.ENUM('SESSAO_ESTUDO', 'TAREFA', 'AJUSTE_ADMIN', name='origem_pontos'), nullable=False),
        sa.Column('descricao', sa.String(length=200), nullable=True),
        sa.Column('criado_por_id', sa.UUID(), nullable=True),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('chave_idempotencia', sa.String(length=80), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.CheckConstraint('pontos <> 0', name=op.f('ck_point_ledger_lancamento_nao_pode_ser_zero')),
        sa.ForeignKeyConstraint(['beneficiario_id'], ['users.id'], name=op.f('fk_point_ledger_beneficiario_id_users'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], name=op.f('fk_point_ledger_criado_por_id_users'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['familia_id'], ['families.id'], name=op.f('fk_point_ledger_familia_id_families'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['materia_id'], ['subjects.id'], name=op.f('fk_point_ledger_materia_id_subjects'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['objetivo_id'], ['objectives.id'], name=op.f('fk_point_ledger_objetivo_id_objectives'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['ocorrencia_id'], ['objective_occurrences.id'], name=op.f('fk_point_ledger_ocorrencia_id_objective_occurrences'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['sessao_id'], ['study_sessions.id'], name=op.f('fk_point_ledger_sessao_id_study_sessions'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_point_ledger')),
        sa.UniqueConstraint('chave_idempotencia', name=op.f('uq_point_ledger_chave_idempotencia'))
        )
        op.create_table('screen_captures',
        sa.Column('sessao_id', sa.UUID(), nullable=False),
        sa.Column('usuario_id', sa.UUID(), nullable=False),
        sa.Column('familia_id', sa.UUID(), nullable=False),
        sa.Column('caminho', sa.String(length=500), nullable=False),
        sa.Column('caminho_miniatura', sa.String(length=500), nullable=True),
        sa.Column('sha256', sa.String(length=64), nullable=False),
        sa.Column('bytes_tamanho', sa.Integer(), nullable=False),
        sa.Column('mime', sa.String(length=40), nullable=False),
        sa.Column('largura', sa.Integer(), nullable=True),
        sa.Column('altura', sa.Integer(), nullable=True),
        sa.Column('capturada_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('recebida_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', postgresql.ENUM('PENDENTE', 'RECEBIDA', 'INVALIDA', 'EXPIRADA', name='status_captura'), nullable=False),
        sa.Column('tela_protegida', sa.Boolean(), nullable=False),
        sa.Column('remover_em', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.CheckConstraint('bytes_tamanho > 0', name=op.f('ck_screen_captures_tamanho_positivo')),
        sa.ForeignKeyConstraint(['familia_id'], ['families.id'], name=op.f('fk_screen_captures_familia_id_families'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sessao_id'], ['study_sessions.id'], name=op.f('fk_screen_captures_sessao_id_study_sessions'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name=op.f('fk_screen_captures_usuario_id_users'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_screen_captures')),
        sa.UniqueConstraint('sessao_id', 'sha256', name='captura_sem_duplicata')
        )
        op.create_table('session_events',
        sa.Column('sessao_id', sa.UUID(), nullable=False),
        sa.Column('tipo', sa.String(length=60), nullable=False),
        sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('dados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('origem', sa.String(length=20), nullable=False),
        sa.Column('sequencia', sa.BigInteger(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['sessao_id'], ['study_sessions.id'], name=op.f('fk_session_events_sessao_id_study_sessions'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_session_events')),
        sa.UniqueConstraint('sessao_id', 'sequencia', name='sequencia_unica_na_sessao')
        )
        op.create_table('session_locations',
        sa.Column('sessao_id', sa.UUID(), nullable=False),
        sa.Column('captura_id', sa.UUID(), nullable=True),
        sa.Column('local_conhecido_id', sa.UUID(), nullable=True),
        sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column('precisao_metros', sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column('medida_em_dispositivo', sa.DateTime(timezone=True), nullable=True),
        sa.Column('recebida_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('idade_leitura_seg', sa.Integer(), nullable=True),
        sa.Column('simulada', sa.Boolean(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_session_locations_latitude_valida')),
        sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_session_locations_longitude_valida')),
        sa.ForeignKeyConstraint(['captura_id'], ['screen_captures.id'], name=op.f('fk_session_locations_captura_id_screen_captures'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['local_conhecido_id'], ['known_locations.id'], name=op.f('fk_session_locations_local_conhecido_id_known_locations'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['sessao_id'], ['study_sessions.id'], name=op.f('fk_session_locations_sessao_id_study_sessions'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_session_locations'))
        )
        op.create_index('ix_users_ativo', 'users', ['ativo'], unique=False)
        op.create_index('ix_audit_familia_tempo', 'audit_logs', ['familia_id', 'ocorrido_em'], unique=False)
        op.create_index('ix_audit_recurso', 'audit_logs', ['recurso_tipo', 'recurso_id'], unique=False)
        op.create_index('ix_family_members_familia_papel', 'family_members', ['familia_id', 'papel'], unique=False)
        op.create_index('ix_notifications_nao_lidas', 'notifications', ['destinatario_id', 'criada_em'], unique=False, postgresql_where=sa.text('lida_em IS NULL'))
        op.create_index('ix_refresh_tokens_usuario_validade', 'refresh_tokens', ['usuario_id', 'expira_em'], unique=False)
        op.create_index('ix_tracks_beneficiario', 'reward_tracks', ['beneficiario_id'], unique=False)
        op.create_index('ix_objectives_titular_status', 'objectives', ['titular_id', 'status'], unique=False)
        op.create_index('ix_objectives_familia', 'objectives', ['familia_id'], unique=False)
        op.create_index('ix_occurrences_status_data', 'objective_occurrences', ['status', 'prevista_para'], unique=False)
        op.create_index('ix_occurrences_titular_data', 'objective_occurrences', ['titular_id', 'prevista_para'], unique=False)
        op.create_index('ix_sessions_objetivo', 'study_sessions', ['objetivo_id'], unique=False)
        op.create_index('ix_sessions_familia_estado', 'study_sessions', ['familia_id', 'estado'], unique=False)
        op.create_index('ix_sessions_usuario_inicio', 'study_sessions', ['usuario_id', 'iniciada_em'], unique=False)
        op.create_index('ix_ledger_materia', 'point_ledger', ['materia_id'], unique=False)
        op.create_index('ix_ledger_familia_data', 'point_ledger', ['familia_id', 'criado_em'], unique=False)
        op.create_index('ix_ledger_beneficiario_data', 'point_ledger', ['beneficiario_id', 'criado_em'], unique=False)
        op.create_index('ix_captures_sessao_tempo', 'screen_captures', ['sessao_id', 'capturada_em'], unique=False)
        op.create_index('ix_captures_expiracao', 'screen_captures', ['remover_em'], unique=False)
        op.create_index('ix_session_events_sessao_tempo', 'session_events', ['sessao_id', 'ocorrido_em'], unique=False)
        op.create_index('ix_locations_sessao', 'session_locations', ['sessao_id'], unique=False)
        op.create_foreign_key('fk_occurrence_sessao_conclusao', 'objective_occurrences', 'study_sessions', ['sessao_conclusao_id'], ['id'], ondelete='SET NULL', use_alter=True)
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_constraint('fk_occurrence_sessao_conclusao', 'objective_occurrences', type_='foreignkey')
        op.drop_index('ix_locations_sessao', table_name='session_locations')
        op.drop_table('session_locations')
        op.drop_index('ix_session_events_sessao_tempo', table_name='session_events')
        op.drop_table('session_events')
        op.drop_index('ix_captures_sessao_tempo', table_name='screen_captures')
        op.drop_index('ix_captures_expiracao', table_name='screen_captures')
        op.drop_table('screen_captures')
        op.drop_index('ix_ledger_materia', table_name='point_ledger')
        op.drop_index('ix_ledger_familia_data', table_name='point_ledger')
        op.drop_index('ix_ledger_beneficiario_data', table_name='point_ledger')
        op.drop_table('point_ledger')
        op.drop_index('ix_sessions_objetivo', table_name='study_sessions')
        op.drop_index('ix_sessions_familia_estado', table_name='study_sessions')
        op.drop_index('ix_sessions_usuario_inicio', table_name='study_sessions')
        op.drop_table('study_sessions')
        op.drop_table('reward_unlocks')
        op.drop_index('ix_occurrences_status_data', table_name='objective_occurrences')
        op.drop_index('ix_occurrences_titular_data', table_name='objective_occurrences')
        op.drop_table('objective_occurrences')
        op.drop_table('reward_levels')
        op.drop_index('ix_objectives_titular_status', table_name='objectives')
        op.drop_index('ix_objectives_familia', table_name='objectives')
        op.drop_table('objectives')
        op.drop_table('subjects')
        op.drop_index('ix_tracks_beneficiario', table_name='reward_tracks')
        op.drop_table('reward_tracks')
        op.drop_index('ix_refresh_tokens_usuario_validade', table_name='refresh_tokens')
        op.drop_table('refresh_tokens')
        op.drop_index('ix_notifications_nao_lidas', table_name='notifications', postgresql_where=sa.text('lida_em IS NULL'))
        op.drop_table('notifications')
        op.drop_table('known_locations')
        op.drop_index('ix_family_members_familia_papel', table_name='family_members')
        op.drop_table('family_members')
        op.drop_index('ix_audit_familia_tempo', table_name='audit_logs')
        op.drop_index('ix_audit_recurso', table_name='audit_logs')
        op.drop_table('audit_logs')
        op.drop_table('families')
        op.drop_table('devices')
        op.drop_index('ix_users_ativo', table_name='users')
        op.drop_table('users')
        # ### end Alembic commands ###
